apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-phronesis-cert
  namespace: monitoring
spec:
  secretName: wildcard-phronesis-cert
  dnsNames:
  - 'phronesis.cloud'
  - '*.phronesis.cloud'
  acme:
    config:
    - dns01:
        provider: cloudflare
      domains:
      - 'phronesis.cloud'
      - '*.phronesis.cloud'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
